NumPy is the fundamental package for scientific computing with Python. It contains among other things:
<br>

1) a powerful N-dimensional array object
<br>
2) sophisticated (broadcasting) functions
<br>
3) tools for integrating C/C++ and Fortran code
<br>
4) useful linear algebra, Fourier transform, and random number capabilities


In [3]:
dataset = [[1, 1], [2, 3], [4, 3], [3, 2], [5, 5], [6,6]]
print(type(dataset))

<class 'list'>


In [4]:
import numpy as np
dataset = np.array(dataset)
print(dataset)
print(type(dataset))

[[1 1]
 [2 3]
 [4 3]
 [3 2]
 [5 5]
 [6 6]]
<class 'numpy.ndarray'>


In [31]:
dataset.size

12

In [35]:
dataset.shape

(6, 2)

In [33]:
dataset.dtype

dtype('int32')

In [32]:
dataset.ndim

2

In [34]:
type(dataset.shape)

tuple

In [24]:
print(dataset[:,0])
print(dataset[:,1])

[1 2 4 3 5 6]
[1 3 3 2 5 6]


In [37]:
dataset[0]

1

In [40]:
dataset[2,0]  #dataset[2][0] both are same

4

In [42]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [43]:
b = np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
c= np.array(((1,2,3),(4,5,6)), dtype=complex)
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [51]:
c[0][2]

(3+0j)

In [53]:
d=np.zeros((3,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
e=np.ones((2,2), dtype = np.int16)
e

array([[1, 1],
       [1, 1]], dtype=int16)

In [59]:
f=np.arange(10,50,5)       #starting no, below max range , increment
f

array([10, 15, 20, 25, 30, 35, 40, 45])

In [60]:
g=np.linspace(10,20,10)     #starting no , last no, count of equal partitions
g

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [65]:
h=np.arange(6)
h

array([0, 1, 2, 3, 4, 5])

In [66]:
h=h.reshape(2,3)
h

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
h<2

array([[ True,  True, False],
       [False, False, False]])

In [73]:
i=np.arange(0,100000,10).reshape(100,100)
i

array([[    0,    10,    20, ...,   970,   980,   990],
       [ 1000,  1010,  1020, ...,  1970,  1980,  1990],
       [ 2000,  2010,  2020, ...,  2970,  2980,  2990],
       ...,
       [97000, 97010, 97020, ..., 97970, 97980, 97990],
       [98000, 98010, 98020, ..., 98970, 98980, 98990],
       [99000, 99010, 99020, ..., 99970, 99980, 99990]])

In [77]:
j = np.array(([1,0],[3,5]))
k = np.array(([3,6],[5,6]))
j*k      #element wise product

array([[ 3,  0],
       [15, 30]])

In [78]:
np.dot(j,k)     #matrix multiplication

array([[ 3,  6],
       [34, 48]])

# Reshape

In [10]:
x=np.array((825,215,1070,550,480,920,1350,325,670,1215))
print("orginal np array\n")
print(x)
x = x.reshape(-1,1)
print("\nnp array after reshape -1 row auto adjust with 1 column (-1,1)\n")
print(x)
print("\nnp array after reshape -1 row auto adjust,  with 2 columns (-1,2)\n")
x = x.reshape(-1,2)
print(x)

orginal np array

[ 825  215 1070  550  480  920 1350  325  670 1215]

np array after reshape -1 row auto adjust with 1 column (-1,1)

[[ 825]
 [ 215]
 [1070]
 [ 550]
 [ 480]
 [ 920]
 [1350]
 [ 325]
 [ 670]
 [1215]]

np array after reshape -1 row auto adjust,  with 2 columns (-1,2)

[[ 825  215]
 [1070  550]
 [ 480  920]
 [1350  325]
 [ 670 1215]]
